### ISSUE TITLE
Error: Cannot find module 'vue' | 2.4.6

### ISSUE THREAD

**Issue by zraineri** [Trinovantes/puppeteer-prerender-plugin#2]
Newest update causes the error "Cannot find module 'vue'"

```shell
[webpack-cli] Error: Cannot find module 'vue'
Require stack:
- node_modules\@vue\server-renderer\dist\server-renderer.cjs.js
- node_modules\@vue\server-renderer\index.js
- node_modules\puppeteer-prerender-plugin\dist\utils\VueSsrRenderer.js
- node_modules\puppeteer-prerender-plugin\dist\servers\VueSsgServer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:5:11)
    at Module._compile (node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules\\@vue\\server-renderer\\dist\\server-renderer.cjs.js',
    'node_modules\\@vue\\server-renderer\\index.js',
    'node_modules\\puppeteer-prerender-plugin\\dist\\utils\\VueSsrRenderer.js',
    'node_modules\\puppeteer-prerender-plugin\\dist\\servers\\VueSsgServer.js'
  ]
}
```

I removed my starting directory from above. Solved by reverting to 2.4.5. I'm not using vue and adding vue as a dependency did not correct the issue

Thanks for all your hard work!

**Comment by Trinovantes** [comment]
Let me know if 2.4.7 resolves the issues
