### ISSUE TITLE
  [webpack-cli] Error: Protocol error (Page.navigate): Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by masx200** [Trinovantes/puppeteer-prerender-plugin#7]
this error occured on nodejs 17.

`http://::1:64326/`  this is not a valid ipv6 url

```
 <i> [PuppeteerPrerenderPlugin] Initializing PrerenderServer


 <i> [PuppeteerPrerenderPlugin] Initializing PrerenderServer index.html


 <i> [PuppeteerPrerenderPlugin] Serving static content from D:\Documents\GitHub\markdown-reader\dist to /


 <i> [PuppeteerPrerenderPlugin] Initializing Puppeteer


 <i> [PuppeteerPrerenderPlugin] Rendering http://::1:64326/bWQ9aHR0cHMlM0ElMkYlMkZjZG4uanNkZWxpdnIubmV0JTJGZ2glMkZtYXN4MjAwJTJGbWFya2Rvd24tcmVhZGVyJTQwbWFpbiUyRlJFQURNRS5tZA==


 <i> [PuppeteerPrerenderPlugin] Rendering http://::1:64326/bWQ9aHR0cHMlM0ElMkYlMkZjZG4uanNkZWxpdnIubmV0JTJGZ2glMkZtYXN4MjAwJTJGbWFya2Rvd24tcmVhZGVyJTQwbWFpbiUyRmRvY3MlMkZzdHlsZS5tZA==


 <i> [PuppeteerPrerenderPlugin] Rendering http://::1:64326/bWQ9aHR0cHMlM0ElMkYlMkZjZG4uanNkZWxpdnIubmV0JTJGZ2glMkZtYXN4MjAwJTJGbWFya2Rvd24tcmVhZGVyJTQwbWFpbiUyRmRvY3MlMkZtYXRoc19kZW1vLm1k

<i> [PuppeteerPrerenderPlugin] Rendering http://::1:64326/bWQ9aHR0cHMlM0ElMkYlMkZjZG4uanNkZWxpdnIubmV0JTJGZ2glMkZtYXN4MjAwJTJGbWFya2Rvd24tcmVhZGVyJTQwbWFpbiUyRmRvY3MlMkZyZWFkbWUubWQ=


 <i> [PuppeteerPrerenderPlugin] Rendering http://::1:64326/bWQ9aHR0cHMlM0ElMkYlMkZjZG4uanNkZWxpdnIubmV0JTJGZ2glMkZtYXN4MjAwJTJGbWFya2Rvd24tcmVhZGVyJTQwbWFpbiUyRmRvY3MlMkZob3dfZG9faV91c2VfZGl0dG8ubWQ=

 [webpack-cli] Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
  at D:\Documents\GitHub\markdown-reader\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217:63

  at new Promise (<anonymous>)

  at CDPSession.send (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:216:16)

  at navigate (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:108:47)

  at FrameManager.navigateFrame (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:91:13)

  at Frame.goto (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:416:41)

  at Page.goto (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1149:53)

  at PuppeteerPrerenderPlugin.renderRouteWithPuppeteer (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer-prerender-plugin\dist\PuppeteerPrerenderPlugin.js:146:20)

  at processTicksAndRejections (node:internal/process/task_queues:96:5)

  at async PuppeteerPrerenderPlugin.renderRoute (D:\Documents\GitHub\markdown-reader\node_modules\puppeteer-prerender-plugin\dist\PuppeteerPrerenderPlugin.js:100:30)


child process exited with code 2
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

PS D:\Documents\GitHub\markdown-reader> cat package.json
{
  
  "devDependencies": {
    "@types/autoprefixer": "^10.2.0",
    "@types/core-js": "^2.5.5",
    "@types/cssnano": "^4.0.1",
    "@types/cssom": "^0.4.1",
    "@types/escape-html": "^1.0.1",
    "@types/find": "^0.2.1",
    "@types/fs-extra": "^9.0.12",
    "@types/html-minifier-terser": "^5.1.2",
    "@types/jsdom": "^16.2.13",
    "@types/loader-utils": "^2.0.3",
    "@types/lodash": "^4.14.171",
    "@types/marked": "^4.0.1",
    "@types/node-fetch": "^2.5.12",
    "@types/regenerator-runtime": "^0.13.1",
    "atob": "^2.1.2",
    "autoprefixer": "^10.3.4",
    "btoa": "^1.2.1",
    "cssom": "^0.5.0",
    "husky": "^7.0.1",
    "jest-worker": "^27.1.0",
    "mathjax-full": "^3.2.0",
    "postcss": "8.3.6",
    "postcss-preset-env": "6.7.0",
    "puppeteer-prerender-plugin": "^3.0.5",
    "resolve-url-loader": "^5.0.0-beta.1",
    "rollup-external-modules": "^2.0.0"
  },
  
  "dependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/preset-react": "^7.14.5",
    "@highlightjs/cdn-assets": "^11.1.0",
    "@masx200/event-emitter-target": "^1.1.9",
    "@masx200/ie11-usual-polyfills": "^1.0.5",
    "@masx200/mathjax-module-async": "^1.4.3",
    "@masx200/search-hash-params-router": "^2.1.0",
    "@masx200/webpack-react-vue-spa-awesome-config": "^4.3.6",
    "@patarapolw/scope-css": "^1.3.0",
    "@rollup/plugin-babel": "^5.3.0",
    "@rollup/plugin-commonjs": "^20.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^13.0.4",
    "@vue/compiler-sfc": "^3.2.12",
    "babel-loader": "^8.2.2",
    "bootstrap": "^5.1.0",
    "clipboard": "^2.0.8",
    "core-js": "3",
    "cross-env": "^7.0.3",
    "cssnano": "^5.0.8",
    "escape-html": "^1.0.3",
    "find": "^0.3.0",
    "fs-extra": "^10.0.0",
    "highlight.js": "^11.2.0",
    "html-loader": "^2.1.2",
    "html-minifier-terser": "^6.0.0",
    "html-webpack-plugin": "^5.3.2",
    "jsdom": "^17.0.0",
    "loader-utils": "^2.0.0",
    "lodash": "^4.17.21",
    "marked": "^4.0.10",
    "node-fetch": "^2.6.1",
    "postcss": "^8.3.6",
    "postcss-custom-properties": "^11.0.0",
    "postcss-preset-env": "^6.7.0",
    "postcss-values-parser": "^6.0.0",
    "prettier": "2.3.2",
    "regenerator-runtime": "^0.13.9",
    "rollup": "^2.56.3",
    "rollup-plugin-define": "^1.0.1",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-ts": "^1.4.0",
    "sass-loader": "^12.1.0",
    "schema-utils": "^3.1.1",
    "terser": "^5.7.1",
    "terser-webpack-plugin": "^5.1.4",
    "tslib": "^2.3.0",
    "typescript": "^4.4.3",
    "vue": "^3.2.12",
    "webpack": "^5.47.0",
    "webpack-cli": "^4.7.2"
  }
}
PS D:\Documents\GitHub\markdown-reader> node -v
v17.3.1
```

**Comment by masx200** [comment]
webpack.config.js


https://github.com/masx200/markdown-reader/blob/c5e17a39ddaedade2c5514b790a6ae08c2836dd5/config/webpack.config.js#L55

**Comment by masx200** [comment]
thank you ,it works well
